BEGIN;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "thumbnailImageKey" TEXT;
ALTER TABLE "User" ALTER COLUMN "email" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "password" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "password" DROP DEFAULT;
COMMIT;
